### ISSUE TITLE
Daylight Savings behaviour is not tested

### ISSUE THREAD

**Issue by GalenReich** [bellingcat/ShadowFinder#10]
It is not clear to me if daylight savings is correctly handled. Would be good to check and document,

**Comment by tomellm** [comment]
Hey, I have been looking at a few different issues thinking of getting into contributing and this one caught my eye. 

Before I spend any actual time working on the issue I just wanted to validate some thoughts. Okay if I understand correctly daylight savings depends on the location the date-time comes from. This means that it depends on the user, there is no way for us to know if the received date-time contains a daylight savings offset, well except if the user provides timezone information. Meaning whatever we do we need to request more information from the user or in some way notify the user where the errors might show up.

Not sure if my thoughts are correct but please tell me what you think.

**Comment by GalenReich** [comment]
Hi @tomellm, thanks for reaching out. We have a thread (called `Shadow length ratio plotting`) discussing this in our Discord server if you'd be interested in joining: https://discord.gg/bellingcat

There are definitely some challenges with this method, at the moment a user can either provide the time in UTC (in which case daylight savings isn't relevant) or in local time (in which case daylight savings could make a big difference).

The current approach to handling local time is to calculate the UTC offset at a grid of points on the Earth's surface, and transform the "local time" into UTC (which will be different in different timezones). Because timezones are not continuous, there are discontinuities in the output (see China and India in the following image for the most prominent examples):

![image](https://github.com/bellingcat/ShadowFinder/assets/54807169/059468be-46dd-4518-aeba-e9d2f278a43f)

The question posed by this issue is whether daylight savings is included in the UTC offset calculation made for the grid of points on the Earth's surface - we know the date, so in principle there is enough information to know if the location is in daylight savings or not.

Hope that helps!

**Comment by tomellm** [comment]
Hey @GalenReich, thanks for the wonderful answer, it seems I heavily misunderstood the problem, and jumped on it too quickly. I found the thread on discord and am looking through it as of now to better understand exactly how to tackle this. Your answer has already cleared up a lot of misconceptions in my mind, I will come back to you if I come to any conclusions. 

Thanks a lot!

**Comment by GalenReich** [comment]
Daylight savings is now handled by pytz
