### ISSUE TITLE
Add direct solar angle input

### ISSUE THREAD

**Issue by GalenReich** [bellingcat/ShadowFinder#5]
Currently, the program asks for an object height and shadow length, which is used to calculate solar altitude angle.

There may be situations where it is advantageous to input solar altitude angle directly.

It would be good to support this as an alternate input.

**Comment by tomellm** [comment]
@GalenReich If you don't mind I would like to give this one a try.

I looked throught the code and in my understanding you are talking about having the user provide this?
https://github.com/bellingcat/ShadowFinder/blob/cf386d4d171bb5046ba00376612370184d9babfa/shadowfinder/shadowfinder.py#L137-L139

**Comment by GalenReich** [comment]
Great! 

It is related to that. At the moment the tool takes input for `object_height` and `shadow_length`

This part of the calculation takes all of the points around the world and evaluates how long a shadow of an object with height `object_height` would be at the given date and time.

https://github.com/bellingcat/ShadowFinder/blob/cf386d4d171bb5046ba00376612370184d9babfa/shadowfinder/shadowfinder.py#L141-L144

It then compares the `shadow_length` it was given with the `shadown_lengths` (note the plural) as they would be found all around the world.

It would be good to be able to provide the solar angle directly (instead of `object_height` and `shadow_length`). But how this would be propagated in the code is up to you/for discussion!

The relationship is: $`\tan\left(\text{solar angle}\right) = \frac{\text{object height}}{\text{shadow length}}`$

One option would be to use the angle to calculate `shadow_length` for `object_height = 1`:

```python
object_height = 1
shadow_length = object_height / np.tan(solar_angle) 
```

Watch out for angles in radians vs degrees! 

I hope that helps!

**Comment by tomellm** [comment]
okay... are the `shadow_length` and `object_height` still needed in this case? If I understand the procedure correctly you do the following:
- get a list of sun altitudes for every square
- calculate the shadow length for every single square
- mask out where the sun is under the horizon
- and then calculate the relative difference between the given shadow and the actual shadow

But since we already have the sun altitude could we not skip step 2 and in step 4 calculate the difference between the actual and the given sun altitude?

**Comment by GalenReich** [comment]
This is a good question, you are definitely right that we could do that! My only thinking is that it's often good to show the user the same type of output. But as the results might look quite similar, I'd suggest having a go and seeing what it looks like :)

**Comment by tomellm** [comment]
first draft of the PR is up #13, please check it out ;)
